const FilteredData = [
  {
    courseId: "Maths_Learning",
    1: [
      "Pre-number Concepts",
      "Shapes",
      "Numbers 1 to 10",
      "Shapes and Patterns",
      "Ordinal Numbers",
      "Money",
      "Addition",
      "Numbers",
      "Time",
    ],
    2: [
      "Numbers",
      "Data Handling",
      "Subtraction",
      "Addition",
      "Money",
      "Multiplication",
      "Geometry",
      "Measurement",
      "Division",
      "Patterns",
      "Fractions",
    ],
    3: [
      "Division",
      "Numbers and Numeration",
      "Subtraction",
      "Money",
      "Fractions",
      "Multiplication",
      "Geometry",
      "Measurement",
      "Data Handling",
      "Addition",
      "Time",
      "Patterns",
    ],
    4: [
      "Data Handling",
      "Decimals",
      "Fractions",
      "Time",
      "Numbers and Numeration",
      "Subtraction",
      "Geometry",
      "Multiplication",
      "Division",
      "Money",
      "Addition",
      "Measurement",
    ],
    5: [
      "Division",
      "Subtraction",
      "Data Handling",
      "Measurement",
      "Numbers",
      "Multiplication",
      "Time",
      "Money",
      "Addition",
      "Decimals",
      "Fractions",
      "Geometry",
    ],
    6: [
      "Geometry",
      "Integers",
      "Algebra",
      "Ratio and Proportion",
      "Decimals",
      "Data Handling",
      "Fractions",
      "Practical Geometry",
      "Symmetry",
      "Whole Numbers",
      "Mensuration",
    ],
    7: [
      "Rational Numbers",
      "Mensuration",
      "Fractions and Decimals",
      "Practical Geometry",
      "Data Handling",
      "Algebraic Expressions",
      "Number System",
      "Ratio and Proportion",
      "Exponents and Powers",
      "Linear Equations",
      "Geometry",
    ],
    8: [
      "Cube and Cube Roots",
      "Mensuration",
      "Exponents and Powers",
      "Number System",
      "Algebraic Expressions",
      "Data Handling",
      "Linear Equations",
      "Square and Square Roots",
      "Direct and Inverse Proportion",
      "Geometry",
      "Practical Geometry",
    ],
    9: [
      "Polynomials",
      "Linear Equations",
      "Circles",
      "Quadrilaterals",
      "Areas of Parallelograms and Triangles",
      "Lines and Angles",
      "Triangles",
      "Constructions",
      "Introduction to Euclid's Geometry",
      "Rational Numbers",
      "Coordinate Geometry",
    ],
    10: [
      "Constructions",
      "Introduction to Trigonometry",
      "Coordinate Geometry",
      "Probability",
      "Pair of Linear Equations in Two Variables",
      "Quadratic Equations",
      "Polynomials",
      "Circles",
      "Arithmetic Progressions",
      "Number Systems",
      "Statistics",
      "Triangles",
      "Applications of Trigonometry",
    ],
  },
  {
    courseId: "Science_Learning",
    1: [
      "Plants",
      "Water",
      "Animals",
      "Food",
      "Light and Shadow",
      "Earth and Sky",
      "Weather and Seasons",
      "Human Body",
      "Living and Non-Living Things",
      "Materials",
      "Sound",
    ],
    2: [
      "Water",
      "Air",
      "Human Body",
      "Weather and Seasons",
      "Food",
      "Materials",
      "Sound",
      "Earth and Sky",
      "Animals",
      "Plants",
      "Light",
    ],
    3: [
      "Air",
      "Light",
      "Food",
      "Forces and Motion",
      "Water",
      "Sound",
      "Weather and Seasons",
      "Human Body",
      "Animals",
      "Rocks and Soils",
      "Plants",
    ],
    4: [
      "Sound",
      "Electricity",
      "Air",
      "Human Body",
      "Light",
      "Forces and Motion",
      "Plants",
      "Food",
      "Water",
      "Materials",
      "Animals",
    ],
    5: [
      "Water",
      "Sound",
      "Human Body",
      "Air",
      "Food",
      "Forces and Motion",
      "Materials",
      "Electricity and Magnetism",
      "Light",
      "Soil",
      "Plants",
      "Animals",
    ],
    6: [
      "Fabrics",
      "Light",
      "Shadows",
      "and Reflection",
      "Air and Atmosphere",
      "Animals",
      "Natural Resources",
      "Human Body",
      "Electricity and Circuits",
      "Magnets and Magnetism",
      "Plants",
      "Water",
      "Food and Nutrition",
      "Materials",
    ],
    7: [
      "Soil",
      "Heat",
      "Winds",
      "Storms",
      "and Cyclones",
      "Reproduction in Plants",
      "Transportation in Animals and Plants",
      "Nutrition in Animals",
      "Acids",
      "Bases",
      "and Salts",
      "Physical and Chemical Changes",
      "Nutrition in Plants",
      "Respiration in Organisms",
      "Weather",
      "Climate",
      "and Adaptations",
      "Fibre to Fabric",
    ],
    8: [
      "Synthetic Fibres and Plastics",
      "Coal and Petroleum",
      "Reproduction in Animals",
      "Cell: Structure and Functions",
      "Crop Production and Management",
      "Materials: Metals and Non-Metals",
      "Microorganisms: Friend and Foe",
      "Sound",
      "Friction",
      "Force and Pressure",
      "Conservation of Plants and Animals",
      "Combustion and Flame",
      "Reaching the Age of Adolescence",
    ],
    9: [
      "Carbon and Its Compounds",
      "Heredity and Evolution",
      "Reproduction in Organisms",
      "Electricity",
      "Magnetic Effects of Electric Current",
      "Light: Reflection and Refraction",
      "Life Processes",
      "Chemical Reactions and Equations",
      "Control and Coordination",
      "The Human Eye and the Colourful World",
      "Acids",
      "Bases",
      "and Salts",
      "Periodic Classification of Elements",
      "Metals and Non-Metals",
      "Sources of Energy",
    ],
    10: [
      "Metals and Non-Metals",
      "Carbon and Its Compounds",
      "Control and Coordination",
      "Heredity and Evolution",
      "Life Processes",
      "Periodic Classification of Elements",
      "Reproduction",
      "Electricity",
      "Acids",
      "Bases",
      "and Salts",
      "Chemical Reactions",
      "Magnetic Effects of Electric Current",
      "Sources of Energy",
      "Light",
    ],
  },
  {
    courseId: "English_Learning",
    1: [
      "Rhymes and Songs",
      "Picture Reading",
      "Basic Vocabulary",
      "Writing Skills",
      "Sentence Formation",
      "Reading Comprehension",
      "Storytelling",
      "Alphabets and Phonics",
      "Grammar Basics",
      "Listening and Speaking",
    ],
    2: [
      "Writing Skills",
      "Storytelling",
      "Listening and Speaking",
      "Vocabulary Building",
      "Alphabet Recognition",
      "Grammar",
      "Creative Expression",
      "Phonics and Word Formation",
      "Reading Comprehension",
      "Sentence Structure",
    ],
    3: [
      "Alphabet and Phonics",
      "Storytelling",
      "Creative Writing",
      "Listening and Speaking",
      "Spelling and Vocabulary",
      "Grammar",
      "Reading Comprehension",
      "Vocabulary Development",
      "Writing Skills",
      "Grammar and Sentence Structure",
    ],
    4: [
      "Alphabets and Phonics",
      "Listening and Speaking",
      "Spelling and Vocabulary",
      "Reading Comprehension",
      "Creative Writing",
      "Phonics and Word Formation",
      "Grammar",
      "Vocabulary Expansion",
      "Writing Skills",
      "Storytelling",
    ],
    5: [
      "Grammar",
      "Storytelling",
      "Phonics and Spelling",
      "Creative Writing",
      "Spelling and Vocabulary",
      "Writing Skills",
      "Reading Comprehension",
      "Listening and Speaking",
      "Vocabulary Building",
    ],
    6: [
      "Vocabulary Expansion",
      "Listening and Speaking",
      "Spelling and Vocabulary",
      "Creative Writing",
      "Reading Comprehension",
      "Storytelling",
      "Grammar",
      "Writing Skills",
      "Phonics and Word Formation",
    ],
    7: [
      "Vocabulary Development",
      "Reading Comprehension",
      "Literature",
      "Grammar",
      "Spelling and Vocabulary",
      "Phonics and Spelling",
      "Listening and Speaking",
      "Writing Skills",
      "Creative Writing",
    ],
    8: [
      "Literature",
      "Vocabulary Development",
      "Reading Comprehension",
      "Creative Writing",
      "Spelling and Vocabulary",
      "Writing Skills",
      "Grammar",
      "Listening and Speaking",
      "Phonics and Spelling",
    ],
    9: [
      "Literature",
      "Spelling and Vocabulary",
      "Listening and Speaking",
      "Grammar",
      "Reading Comprehension",
      "Phonics and Spelling",
      "Vocabulary Development",
      "Creative Writing",
      "Writing Skills",
    ],
    10: [
      "Reading Comprehension",
      "Creative Writing",
      "Vocabulary Development",
      "Writing Skills",
      "Spelling",
      "Phonics and Spelling",
      "Grammar",
      "Listening and Speaking",
      "Literature",
    ],
  },
  {
    courseId: "Hindi_Learning",
    1: [
      "Days and Months",
      "Review and Reinforcement",
      "Simple Sentences",
      "Numbers in Hindi",
      "Basic Conversation",
      "Hindi Alphabet",
      "Cultural Awareness",
      "Fun Activities",
      "Basic Vocabulary",
      "Introduction to Hindi",
    ],
    2: [
      "Hindi Vocabulary",
      "Hindi Storytelling",
      "Introduction to Hindi",
      "Daily Conversations in Hindi",
      "Hindi Numbers",
      "Basic Hindi Grammar",
      "Cultural Aspects of Hindi",
      "Hindi Songs and Rhymes",
    ],
    3: [
      "Numbers in Hindi",
      "Simple Words and Phrases",
      "Simple Sentences",
      "Basic Grammar Concepts",
      "Days of the Week and Months",
      "Cultural Aspects",
      "Colors and Shapes",
      "Basic Hindi Alphabets",
      "Family and Relationships",
      "Animals and Nature",
    ],
    4: [
      "Reading Comprehension",
      "Introduction to Hindi",
      "Sentence Formation",
      "Writing Skills",
      "Hindi Vocabulary",
      "Hindi Grammar",
      "Conversational Hindi",
      "Cultural Aspects of Hindi",
    ],
    5: [
      "Writing Skills",
      "Reading Comprehension",
      "Sentence Structure",
      "Vocabulary Building",
      "Hindi Grammar Basics",
      "Listening and Speaking Skills",
      "Cultural Aspects of Hindi Language",
      "Introduction to Hindi",
    ],
    6: [
      "Vocabulary Building",
      "Hindi Alphabet and Script",
      "Introduction to Hindi",
      "Writing Skills",
      "Cultural Context",
      "Reading Comprehension",
      "Basic Grammar",
      "Assessment and Revision",
      "Listening and Speaking Skills",
    ],
    7: [
      "Story Literature",
      "Conversation",
      "Translation",
      "Songs and Poems",
      "Cultural Knowledge",
      "Hindi Alphabet",
      "Grammar",
      "Word Formation",
    ],
    8: [
      "Indian Culture and Literature",
      "Dialogue and Communication",
      "Culture and Society",
      "Poetry and Poetics",
      "Personality Development",
      "Grammar",
      "Development of Language",
      "Story Literature",
    ],

    9: [
      "Reading Comprehension",
      "Cultural Context of Hindi",
      "Writing Skills",
      "Speaking and Listening Skills",
      "Hindi Literature",
      "Vocabulary Building",
      "Basic Hindi Grammar",
    ],
    10: [
      "Speaking and Listening Skills",
      "Writing Skills",
      "Reading Comprehension",
      "Vocabulary Development",
      "Assessment and Evaluation",
      "Grammar Essentials",
      "Cultural Contexts",
    ],
  },
  {
    courseId: "SST_learning",
    1: [
      "Family and Friends",
      "Introduction to Social Studies",
      "Environmental Awareness",
      "Community Helpers",
      "Citizenship and our Rights",
      "Our Country",
      "Understanding Maps",
      "Culture and Traditions",
      "History and Time",
    ],
    2: [
      "Economics and Trade",
      "Government and Leadership",
      "Citizenship and Responsibility",
      "Geography Basics",
      "Cultures Around the World",
      "Our Community",
      "History and Holidays",
    ],
    3: [
      "Government and Citizenship",
      "Global Awareness",
      "Cultural Diversity",
      "Civic Responsibility",
      "Geography Basics",
      "History of Our Nation",
      "Economics for Kids",
      "Environmental Awareness",
      "Introduction to Community",
    ],
    4: [
      "Culture and Society",
      "Current Events",
      "Government and Citizenship",
      "Introduction to Social Studies",
      "History",
      "Geography",
      "Community and Environment",
      "Economics",
    ],
    5: [
      "Government and Citizenship",
      "Environmental Awareness",
      "Geography and Map Skills",
      "Economics and Trade",
      "Historical Timelines",
      "Important Figures in History",
      "Understanding Communities",
      "Cultures and Traditions",
    ],
    6: [
      "Social Justice and Equity",
      "Economics and Trade",
      "Geography and Map Skills",
      "History and Historical Thinking",
      "Cultural Diversity",
      "Government and Citizenship",
      "Current Events",
      "Environmental Responsibility",
    ],
    7: [
      "Government and Citizenship",
      "Culture and Society",
      "Geography and Environment",
      "Economics and Trade",
      "History of Civilizations",
      "Current Events and Global Issues",
    ],
    8: [
      "Current Events",
      "Understanding Geography",
      "Economics",
      "Cultural Studies",
      "World History",
      "Civics and Government",
    ],
    9: [
      "Current Events and Global Issues",
      "Personal Finance and Economics",
      "Introduction to Social Studies",
      "History and Civilizations",
      "Economics and Resources",
      "Geography and Maps",
      "Culture and Society",
      "Government and Citizenship",
    ],
    10: [
      "Culture and Society",
      "Geography",
      "Economics",
      "Civics and Government",
      "Current Events",
      "History",
    ],
  },
];

export default FilteredData;
