[
  {
    courseId: "Biology_Learning",
    11: [
      "Plant Physiology",
      "Cell Structure and Function",
      "Structural Organisation in Animals",
      "Human Physiology",
      "Diversity of the Living World",
    ],
    12: [
      "Ecology and Environment",
      "Genetics and Evolution",
      "Reproduction",
      "Biology and Human Welfare",
    ],
  },
  {
    courseId: "English_Learning",
    11: [
      "Writing Skills",
      "Snapshots (Supplementary Reader)",
      "Reading Comprehension",
      "Hornbill (Prose)",
      "Grammar",
      "Hornbill (Poetry)",
    ],
    12: [
      "Flamingo (Prose)",
      "Reading Comprehension",
      "Flamingo (Poetry)",
      "Writing Skills",
      "Vistas (Supplementary Reader)",
      "Grammar",
    ],
  },
  {
    courseId: "Chemistry_Learning",
    11: [
      "States of Matter",
      "Equilibrium",
      "Organic Chemistry - Some Basic Principles and Techniques",
      "Structure of Atom",
      "The s-Block Elements (Alkali and Alkaline Earth Metals)",
      "Hydrocarbons",
      "Classification of Elements and Periodicity in Properties",
      "Thermodynamics",
      "Chemical Bonding and Molecular Structure",
      "Environmental Chemistry",
      "Redox Reactions",
      "Some Basic Concepts of Chemistry",
      "Hydrogen",
      "The p-Block Elements (Group 13 and 14)",
    ],
    12: [
      "Chemical Kinetics",
      "Alcohols, Phenols, and Ethers",
      "Polymers",
      "Surface Chemistry",
      "Solid State",
      "Organic Compounds Containing Nitrogen",
      "Aldehydes, Ketones, and Carboxylic Acids",
      "Coordination Compounds",
      "Electrochemistry",
      "The d- and f-Block Elements",
      "Solutions",
      "Haloalkanes and Haloarenes",
      "Biomolecules",
      "General Principles and Processes of Isolation of Elements",
      "The p-Block Elements",
      "Chemistry in Everyday Life",
    ],
  },
  {
    courseId: "Physics_Learning",
    11: [
      "Behaviour of Perfect Gas and Kinetic Theory",
      "Kinematics",
      "Gravitation",
      "Thermodynamics",
      "Work, Energy, and Power",
      "Physical World and Measurement",
      "Laws of Motion",
      "System of Particles and Rotational Motion",
      "Oscillations and Waves",
      "Properties of Bulk Matter",
    ],
    12: [
      "Ray Optics and Optical Instruments",
      "Electric Charges and Fields",
      "Communication Systems",
      "Electromagnetic Waves",
      "Moving Charges and Magnetism",
      "Dual Nature of Radiation and Matter",
      "Electromagnetic Induction",
      "Magnetism and Matter",
      "Current Electricity",
      "Alternating Current",
      "Semiconductor Electronics",
      "Electrostatic Potential and Capacitance",
      "Wave Optics",
      "Atoms and Nuclei",
    ],
  },
  {
    courseId: "Maths_Learning",
    11: [
      "Sets",
      "Permutations and Combinations",
      "Probability",
      "Sequence and Series",
      "Statistics",
      "Conic Sections",
      "Principle of Mathematical Induction",
      "Linear Inequalities",
      "Straight Lines",
      "Introduction to Three-Dimensional Geometry",
      "Relations and Functions",
      "Trigonometric Functions",
      "Mathematical Reasoning",
      "Complex Numbers and Quadratic Equations",
      "Binomial Theorem",
      "Limits and Derivatives",
    ],
    12: [
      "Determinants",
      "Three-Dimensional Geometry",
      "Vector Algebra",
      "Relations and Functions",
      "Differential Equations",
      "Matrices",
      "Inverse Trigonometric Functions",
      "Linear Programming",
      "Application of Integrals",
      "Continuity and Differentiability",
      "Probability",
      "Integrals",
      "Application of Derivatives",
    ],
  },
  {
    courseId: "Accountancy_Leaning",
    11: [
      "Bank Reconciliation Statement",
      "Trial Balance and Rectification of Errors",
      "Financial Statements of Sole Proprietorship",
      "Basic Accounting Terms",
      "Accounts from Incomplete Records",
      "Accounting Equation",
      "Accounting for Not-for-Profit Organizations",
      "Journal and Ledger",
      "Introduction to Accounting",
      "Depreciation, Provisions, and Reserves",
    ],
  },
  {
    courseId: "B.studies_Learning",
    11: [
      "Nature and Purpose of Business",
      "Internal Trade",
      "Emerging Modes of Business",
      "International Business",
      "Small Business and Entrepreneurship",
      "Sources of Business Finance",
      "Forms of Business Organizations",
      "Business Services",
      "Public, Private and Global Enterprises",
      "Social Responsibility of Business and Business Ethics",
    ],
    12: [
      "Business Environment",
      "Financial Management",
      "Principles of Management",
      "Marketing Management",
      "Directing",
      "Controlling",
      "Nature and Significance of Management",
      "Organizing",
      "Staffing",
      "Planning",
    ],
  },
];
